### ISSUE TITLE
Add setup.py

### ISSUE THREAD

**Issue by ekristen** [PoorBillionaire/USN-Journal-Parser#1]
This would help making this tool more easily install-able.

**Comment by PoorBillionaire** [comment]
Ack - I'll get this one done as well.

**Comment by PoorBillionaire** [comment]
setup.py has been added, and I submitted this one to PyPI. The name in PyPI is 'usnparser', but the installed script will continue to go by 'usn.py'

Let me know if you encounter difficulties with it!

**Comment by ekristen** [comment]
It has been added to the SIFT dev branch, after I finish making the latest updates it'll make its way into the master build, many thanks. https://github.com/sans-dfir/sift-bootstrap/commit/016b1f3cdf95aa29edf134c0ff36603c28d78811
