### ISSUE TITLE
False MFT Number

### ISSUE THREAD

**Issue by JJPED** [PoorBillionaire/USN-Journal-Parser#9]
Hi,

I've tried to use your program but it seems that "sometimes", it makes mistakes when computing MFT Record numbers. For example, I tried to analyze a disk image I made from a Windows 7 system in which I had created a "Fichier_test.txt" (Yes, I'm French ;-) under my Desktop folder.
I had also created a file.txt and a file1.txt in the same Desktop folder.
The MFT Record Number for "Fichier_test.txt" is 24066 and the Parent MFT Record Number is 500.
The MFT Record Number for "file.txt" is 24071 and 24074 for "file1.txt".

However, when I ran your program, I got an unexpected difference of 22560 with the real MFT numbers (that is to say that I got 1506, 1511, and 1514 instead of 24066, 24071 and 24074). However, both their parent MFT Record Number (which is 500) and the other files' MFT Record Numbers seem to be ok. I don't understand how this could happen because I've checked your code and It looks as if it is the same method for computing parent MFT Record Numbers and MFT Record Numbers, but I'm not such an expert in coding, that's why I prefer to contact you.

By the way, I've also cross-checked the results with those I could get with Joshua Schicht UsnJrnl2csv program, and I get the "good" numbers with this last program. Did I misuse the program or is it a true issue ?

Don't hesitate to contact me if you want more explanations, and please forgive me for my English if it is not correct. Moreover, it is the first time I use the "tell issues" option on Github, so I hope it is the good way to do so. If not, please forgive me again.

**Comment by PoorBillionaire** [comment]
@JJPED -

Thank you for the detailed explanation and bug report - I'm looking into this now.

--
Adam

**Comment by PoorBillionaire** [comment]
@JJPED - 

I updated the parser to help resolve this issue. If you wouldn't mind, please validate this against your data and let me know how it looks. The updated script can be found [here](https://github.com/PoorBillionaire/USN-Journal-Parser/tree/jjped-bugfix-branch).

It sounds like you may be relatively new to GitHub, so if you need any assistance pulling the script from this branch, let me know. I appreciate your help.

--
Adam

**Comment by JJPED** [comment]
Hi, 
it seems to work fine for me now.  

Thanks
